site_name: Node-Red
site-author: Peter Groen
google_analytics: ['UA-160983667-1', 'https://dc-smartindustry.github.io/node-red/']
theme: readthedocs
markdown_extensions:
  - admonition
nav:
    - Home: index.md
    - Installatie:
        - installatie.md
        - ibm-cloud.md
        - docker-install.md
        - docker-run.md
    - Node-Red:
        - weerstation.md
    - Hulp: help.md